### ISSUE TITLE
Missing NetworkVersion

### ISSUE THREAD

**Issue by randormi** [LeggyJameh/BetterFirepit#2]
Mod Version 1.1.3
Vintage Story Version 1.19.1

modinfo.json is missing NetworkVersion value causing a download loop when in use on servers. Players are stuck being asked to download from the ModDB when it cannot determine the version.

This can be fixed by adding the NetworkVersion value like so below:

`"NetworkVersion": "1.1.3"`

**Comment by LeggyJameh** [comment]
Thank you for reporting this, the issue should now be fixed!
